# Generated by Django 3.0 on 2025-07-09 13:46

from django.db import migrations


def transfer_data(apps, schema_editor):
    oldModel = apps.get_model('oc_lettings_site', 'Profile')
    newModel = apps.get_model('profiles', 'Profile')
    for old in oldModel.objects.all():
        newModel.objects.create(
            user=old.user,
            favorite_city=old.favorite_city,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_data)
    ]
