# Generated by Django 3.0 on 2025-07-09 13:46

from django.db import migrations


def transfer_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    NewAddress = apps.get_model('lettings', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')

    address_mapping = {}
    for old in OldAddress.objects.all():
        new = NewAddress.objects.create(
            number=old.number,
            street=old.street,
            city=old.city,
            state=old.state,
            zip_code=old.zip_code,
            country_iso_code=old.country_iso_code,
        )
        address_mapping[old.id] = new

    for old in OldLetting.objects.all():
        new_address = address_mapping.get(old.address_id)
        NewLetting.objects.create(
            title=old.title,
            address=new_address,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_data)
    ]
