name: Déploiement du site Orange County Lettings

on:
  push:
    branches:
      - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      SERVER_TYPE: ${{ secrets.SERVER_TYPE }}
      HOSTS: ${{ secrets.HOSTS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8 .
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report term --cov-fail-under=80

  build-push:
      needs: lint-test
      if: github.ref_name == 'master'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build Docker image
          run: |
            GIT_COMMIT=$(git rev-parse --short HEAD)
            docker build -t spleen85/oc-p13:$GIT_COMMIT .
        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Push image
          run: |
            GIT_COMMIT=$(git rev-parse --short HEAD)
            docker push spleen85/oc-p13:$GIT_COMMIT