name: Déploiement du site Orange County Lettings

on:
  push:
    branches:
      - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      SERVER_TYPE: ${{ secrets.SERVER_TYPE }}
      HOSTS: ${{ secrets.HOSTS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8 .
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report term --cov-fail-under=80

  build-push:
    needs: lint-test
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          docker build -t spleen85/oc-p13:$GIT_COMMIT -t spleen85/oc-p13:latest .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push image
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          docker push spleen85/oc-p13:$GIT_COMMIT
          docker push spleen85/oc-p13:latest
      - name: Save commit sha
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  deploy:
    needs: build-push
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      GIT_COMMIT: ${{ needs.build-push.outputs.sha }}
    steps:
      - name: Update env vars on Render
        run: |
          curl -X PATCH "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/env-vars" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{
                  "envVars": [
                    {"key": "SECRET_KEY", "value": "'"${{ secrets.SECRET_KEY }}"'"},
                    {"key": "HOSTS", "value": "'"${{ secrets.HOSTS }}"'"}
                    {"key": "SENTRY_DSN", "value": "'"${{ secrets.SENTRY_DSN }}"'"}
                    {"key": "SERVER_TYPE", "value": "'"${{ secrets.SERVER_TYPE }}"'"}
                  ]
                }'
      - name: display commit git
        run: echo "Commit ${GIT_COMMIT}"
      - name: Trigger deployment on Render
        run: |
          curl "https://api.render.com/deploy/srv-d21b79mmcj7s73c4bo90?key=ObCOrT4qnps"
